version: '3.8'

services:
  database:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_app
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - 'symfony-mysql:/var/lib/mysql'
    networks:
      - symfony-network

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_app
    depends_on:
      - database
    networks:
      - symfony-network

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8090:80'
    volumes:
      - ./app:/var/www/symfony_app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - symfony-network

  consumer:
    build: php
    stop_grace_period: 10s
    command: php bin/console messenger:consume async -vv
    volumes:
      - ./app:/var/www/symfony_app
    depends_on:
      rabbitmq:
        condition: service_started
    networks:
      - symfony-network

    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 30
        window: 120s

  rabbitmq:
#    image: "rabbitmq:3.9-alpine"
    image: rabbitmq:3-management-alpine
#    depends_on:
#      - 'web'
    ports:
      - '5672:5672'
      - '15672:15672'
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq
    depends_on:
      - php
    networks:
      - symfony-network

volumes:
  rabbitmq:
  symfony-mysql:
    driver: local

networks:
  symfony-network:
    driver: bridge